/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  if (knex.client.config.client === 'sqlite3') {
    await knex.raw('PRAGMA foreign_keys = OFF')
  }
  await knex('comments').del()
  await knex('favourites').del()
  await knex('post').del()

  await knex('post').insert([
    {
      id: 1,
      business_name: 'Midnight Espresso',
      business_street: '178 Cuba Street',
      business_suburb: 'Te Aro',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Cafe, Late-Night',
      pet_friendly: true,
      kid_friendly: true,
      vegan: true,
      gluten_free: true,
      outdoor: false,
      indoor: true,
      smoking: false,
      venue_type: 'Cafe',
      parking: false,
      image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5',
      user_id: 'auth0|user1',
      created_by: 'Alex Smith',
      created_by_image: 'https://i.pravatar.cc/150?u=AlexSmith',
      review: 'Great coffee.',
    },

    {
      id: 2,
      business_name: 'Garage Project',
      business_street: '91 Aro Street',
      business_suburb: 'Aro Valley',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Beer, Social',
      pet_friendly: true,
      kid_friendly: false,
      vegan: true,
      gluten_free: true,
      outdoor: true,
      indoor: true,
      smoking: false,
      venue_type: 'Bar',
      parking: false,
      image_url: 'https://images.unsplash.com/photo-1552611052-33e04de081de',
      user_id: 'auth0|user1',
      created_by: 'Alex Smith',
      created_by_image: 'https://i.pravatar.cc/150?u=AlexSmith',
      review: 'Innovative brews.',
    },

    {
      id: 3,
      business_name: 'Wellington Chocolate Factory',
      business_street: '5 Eva Street',
      business_suburb: 'Te Aro',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Organic, Chocolate',
      pet_friendly: false,
      kid_friendly: true,
      vegan: true,
      gluten_free: true,
      outdoor: false,
      indoor: true,
      smoking: false,
      venue_type: 'Cafe',
      parking: false,
      image_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93',
      user_id: 'auth0|user2',
      created_by: 'Jane Doe',
      created_by_image: 'https://i.pravatar.cc/150?u=JaneDoe',
      review: 'Amazing chocolate.',
    },

    {
      id: 4,
      business_name: 'Logan Brown',
      business_street: '192 Cuba Street',
      business_suburb: 'Te Aro',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Dining',
      pet_friendly: false,
      kid_friendly: false,
      vegan: false,
      gluten_free: true,
      outdoor: false,
      indoor: true,
      smoking: false,
      venue_type: 'Restaurant',
      parking: false,
      image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3',
      user_id: 'auth0|user2',
      created_by: 'Jane Doe',
      created_by_image: 'https://i.pravatar.cc/150?u=JaneDoe',
      review: 'Top tier dining.',
    },

    {
      id: 5,
      business_name: 'Prefab',
      business_street: '14 Jessie Street',
      business_suburb: 'Te Aro',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Brunch',
      pet_friendly: true,
      kid_friendly: true,
      vegan: true,
      gluten_free: true,
      outdoor: true,
      indoor: true,
      smoking: false,
      venue_type: 'Cafe',
      parking: false,
      image_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f',
      user_id: 'auth0|user3',
      created_by: 'Sam Brown',
      created_by_image: 'https://i.pravatar.cc/150?u=SamBrown',
      review: 'Spacious brunch spot.',
    },

    {
      id: 6,
      business_name: 'The Roxy Cinema',
      business_street: '5 Park Road',
      business_suburb: 'Miramar',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Cinema',
      pet_friendly: false,
      kid_friendly: true,
      vegan: false,
      gluten_free: true,
      outdoor: false,
      indoor: true,
      smoking: false,
      venue_type: 'Restaurant',
      parking: true,
      image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff',
      user_id: 'auth0|user4',
      created_by: 'Chris White',
      created_by_image: 'https://i.pravatar.cc/150?u=ChrisWhite',
      review: 'Great experience.',
    },

    {
      id: 7,
      business_name: 'Zephyr',
      business_street: '109 Willis Street',
      business_suburb: 'Wellington Central',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Pub',
      pet_friendly: false,
      kid_friendly: false,
      vegan: false,
      gluten_free: false,
      outdoor: true,
      indoor: true,
      smoking: false,
      venue_type: 'Bar',
      parking: false,
      image_url: 'https://images.unsplash.com/photo-1481833761820-0509d3217039',
      user_id: 'auth0|user3',
      created_by: 'Sam Brown',
      created_by_image: 'https://i.pravatar.cc/150?u=SamBrown',
      review: 'Solid local pub.',
    },

    {
      id: 8,
      business_name: 'Beach Babylon',
      business_street: '252 Oriental Parade',
      business_suburb: 'Oriental Bay',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Beachfront',
      pet_friendly: true,
      kid_friendly: true,
      vegan: true,
      gluten_free: true,
      outdoor: true,
      indoor: true,
      smoking: false,
      venue_type: 'Eatery',
      parking: false,
      image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085',
      user_id: 'auth0|user5',
      created_by: 'Pat Green',
      created_by_image: 'https://i.pravatar.cc/150?u=PatGreen',
      review: 'Beautiful view.',
    },

    {
      id: 9,
      business_name: 'Scopa',
      business_street: '141 Cuba Street',
      business_suburb: 'Te Aro',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Pizza',
      pet_friendly: true,
      kid_friendly: true,
      vegan: false,
      gluten_free: false,
      outdoor: true,
      indoor: true,
      smoking: false,
      venue_type: 'Restaurant',
      parking: false,
      image_url: 'https://images.unsplash.com/photo-1559339352-11d035aa65de',
      user_id: 'auth0|user6',
      created_by: 'Taylor Blue',
      created_by_image: 'https://i.pravatar.cc/150?u=TaylorBlue',
      review: 'Great pizza.',
    },

    {
      id: 10,
      business_name: 'Goldings Free Dive',
      business_street: '14 Leeds Street',
      business_suburb: 'Te Aro',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Beer',
      pet_friendly: true,
      kid_friendly: false,
      vegan: true,
      gluten_free: true,
      outdoor: true,
      indoor: true,
      smoking: false,
      venue_type: 'Bar',
      parking: false,
      image_url: 'https://images.unsplash.com/photo-1559339352-11d035aa65de',
      user_id: 'auth0|user7',
      created_by: 'Jordan Black',
      created_by_image: 'https://i.pravatar.cc/150?u=JordanBlack',
      review: 'Cool pub.',
    },
  ])

  if (knex.client.config.client === 'sqlite3') {
    await knex.raw('PRAGMA foreign_keys = ON')
  }

  // If using PostgreSQL, we need to reset the auto-increment sequence
  // because we've inserted records with explicit IDs.
  if (knex.client.config.client === 'postgresql' || knex.client.config.client === 'pg') {
    await knex.raw(
      "SELECT setval(pg_get_serial_sequence('post', 'id'), coalesce(max(id), 1), max(id) IS NOT NULL) FROM post",
    )
  }
}