/**
 * @param { import("knex").Knex } knex
 * @returns { Promise<void> }
 */
export async function seed(knex) {
  // Disable foreign keys temporarily
  await knex.raw('PRAGMA foreign_keys = OFF')
  
  // Deletes ALL existing post entries
  await knex('post').del()

  // Inserts entries
  await knex('post').insert([
    {
      id: 1,
      business_name: 'The Rusty Anchor',
      business_street: '14 Waterfront Lane',
      business_suburb: 'Thorndon',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Nautical, Seafood, Rustic',
      pet_friendly: true,
      kid_friendly: true,
      vegan: false,
      gluten_free: true,
      outdoor: true,
      indoor: true,
      smoking: false,
      venue_type: 'Restaurant',
      parking: true,
      image_url: 'https://images.unsplash.com/photo-1555396273-367ea4eb4db5',
      user_id: 'auth0|444',
      created_by: 'Phoebe Hu',
      created_by_image:
        'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=150&q=80',
      review:
        'A cozy spot with amazing harbor views. The fish and chips are top tier!',
    },
    {
      id: 2,
      business_name: 'Neon Noodle Bar',
      business_street: '88 Cyber Alley',
      business_suburb: 'Te Aro',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Fusion, Late Night, Spicy',
      pet_friendly: false,
      kid_friendly: false,
      vegan: true,
      gluten_free: true,
      outdoor: false,
      indoor: true,
      smoking: false,
      venue_type: 'Eatery',
      parking: false,
      image_url: 'https://images.unsplash.com/photo-1552611052-33e04de081de',
      user_id: 'auth0|123',
      created_by: 'dev_guy',
      created_by_image:
        'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=150&q=80',
      review:
        'Great vibes and even better ramen. Perfect for a late-night coding fuel up.',
    },
    {
      id: 3,
      business_name: 'The Sleepy Fern',
      business_street: '202 Hillside Crescent',
      business_suburb: 'Wadestown',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Quiet, Organic, Local',
      pet_friendly: true,
      kid_friendly: true,
      vegan: true,
      gluten_free: true,
      outdoor: true,
      indoor: true,
      smoking: false,
      venue_type: 'Cafe',
      parking: true,
      image_url: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93',
      user_id: 'auth0|456',
      created_by: 'local_legend',
      created_by_image:
        'https://images.unsplash.com/photo-1599566150163-29194dcaad36?auto=format&fit=crop&w=150&q=80',
      review:
        'Tucked away in the hills. Very dog friendly and the best muffins in the suburb.',
    },
    {
      id: 4,
      business_name: 'Velvet & Vine',
      business_street: '33 Courtenay Quays',
      business_suburb: 'Te Aro',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Wine, Sophisticated, Jazz',
      pet_friendly: false,
      kid_friendly: false,
      vegan: false,
      gluten_free: true,
      outdoor: false,
      indoor: true,
      smoking: false,
      venue_type: 'Bar',
      parking: false,
      image_url: 'https://images.unsplash.com/photo-1510812431401-41d2bd2722f3',
      user_id: 'auth0|admin',
      created_by: 'admin',
      created_by_image:
        'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=150&q=80',
      review:
        'Excellent selection of local Marlborough wines. Great for a date night.',
    },
    {
      id: 5,
      business_name: 'The Pixel Pub',
      business_street: '72 Arcade Way',
      business_suburb: 'Mount Cook',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Gaming, Craft Beer, Social',
      pet_friendly: true,
      kid_friendly: false,
      vegan: true,
      gluten_free: false,
      outdoor: false,
      indoor: true,
      smoking: true,
      venue_type: 'Bar',
      parking: false,
      image_url: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f',
      user_id: 'auth0|789',
      created_by: 'gamer_89',
      created_by_image:
        'https://images.unsplash.com/photo-1527980965255-d3b416303d12?auto=format&fit=crop&w=150&q=80',
      review:
        'Retro consoles and great brews. The smoking area has a nice view of the park.',
    },
    {
      id: 6,
      business_name: 'Breeze Bakery',
      business_street: '5 Ocean Drive',
      business_suburb: 'Island Bay',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Bakery, Fresh, Family',
      pet_friendly: true,
      kid_friendly: true,
      vegan: false,
      gluten_free: false,
      outdoor: true,
      indoor: true,
      smoking: false,
      venue_type: 'Eatery',
      parking: true,
      image_url: 'https://images.unsplash.com/photo-1509440159596-0249088772ff',
      user_id: 'auth0|222',
      created_by: 'test_user_2',
      created_by_image:
        'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=150&q=80',
      review:
        'Best sourdough in Island Bay. Grab a loaf before hitting the beach!',
    },
    {
      id: 7,
      business_name: 'The Iron Kettle',
      business_street: '12 Factory Lane',
      business_suburb: 'Petone',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Industrial, Hearty, Breakfast',
      pet_friendly: false,
      kid_friendly: true,
      vegan: false,
      gluten_free: true,
      outdoor: false,
      indoor: true,
      smoking: false,
      venue_type: 'Cafe',
      parking: true,
      image_url: 'https://images.unsplash.com/photo-1481833761820-0509d3217039',
      user_id: 'auth0|admin',
      created_by: 'admin',
      created_by_image:
        'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=150&q=80',
      review:
        'Huge portions and strong coffee. The industrial decor is very cool.',
    },
    {
      id: 8,
      business_name: 'Summit Sips',
      business_street: '99 Lookout Road',
      business_suburb: 'Brooklyn',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'View, Quick, Friendly',
      pet_friendly: true,
      kid_friendly: true,
      vegan: true,
      gluten_free: true,
      outdoor: true,
      indoor: false,
      smoking: false,
      venue_type: 'Cafe',
      parking: true,
      image_url: 'https://images.unsplash.com/photo-1495474472287-4d71bcdd2085',
      user_id: 'auth0|111',
      created_by: 'hiker_dan',
      created_by_image:
        'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&w=150&q=80',
      review: 'The perfect pit stop after a walk up to the wind turbine.',
    },
    {
      id: 9,
      business_name: 'The Gilded Lily',
      business_street: '21 Boutique Blvd',
      business_suburb: 'Kelburn',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'High Tea, Fancy, Floral',
      pet_friendly: false,
      kid_friendly: true,
      vegan: true,
      gluten_free: true,
      outdoor: true,
      indoor: true,
      smoking: false,
      venue_type: 'Restaurant',
      parking: false,
      image_url: 'https://images.unsplash.com/photo-1559339352-11d035aa65de',
      user_id: 'auth0|555',
      created_by: 'fancy_pants',
      created_by_image:
        'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=150&q=80',
      review:
        'Elegant high tea. Their vegan scone selection is surprisingly vast.',
    },
    {
      id: 10,
      business_name: 'Gravity Garage',
      business_street: '44 Downhill Drive',
      business_suburb: 'Karori',
      business_city: 'Wellington',
      created_at: knex.fn.now(),
      tags: 'Active, Energy, Smoothies',
      pet_friendly: true,
      kid_friendly: true,
      vegan: true,
      gluten_free: true,
      outdoor: true,
      indoor: true,
      smoking: false,
      venue_type: 'Eatery',
      parking: true,
      image_url: 'https://images.unsplash.com/photo-1464349153735-7db50ed83c84',
      user_id: 'auth0|admin',
      created_by: 'admin',
      created_by_image:
        'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=150&q=80',
      review:
        'The hub for mountain bikers. Super chill and they have dog bowls everywhere.',
    },
  ])

  // Re-enable foreign keys
  await knex.raw('PRAGMA foreign_keys = ON')
}
